const products = [
  {
    id: 3001,
    name: "Noir Sultan",
    brand: "NŌRÉVA",
    collection: "VA NOIR",
    category: "men-fragrance",
    tag: "Men",
    price: 1200,
    rating: 4.8,
    reviewCount: 84,
    inspiredBy: "Haltane / Oud Royal",
    description: "Luxurious woody fragrance blended with rich oud and warm spices for a bold masculine presence.",
    details: "Woody oriental scent with deep oud, spice, and a warm luxury trail. Strong projection and long-lasting performance.",
    fragranceFamily: "Woody Oriental",
    performance: "Strong Projection & Long Lasting",
    bottleStyle: "Square Black Bottle",
    tagline: "Power has a scent.",
    gender: "Men",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/noir-sultan.jpg",
    source: "NOREVA",
    offer: true,
    featured: true
  },
  {
    id: 3002,
    name: "Oud Éclipse",
    brand: "NŌRÉVA",
    collection: "VA NOIR",
    category: "men-fragrance",
    tag: "Men",
    price: 1400,
    rating: 4.8,
    reviewCount: 76,
    inspiredBy: "Oud for Greatness",
    description: "A deep mysterious oud fragrance with powerful projection and unforgettable elegance.",
    details: "A rich oud-spicy profile with dark woods and a clean luxury finish. Built for presence, night wear, and special occasions.",
    fragranceFamily: "Oud Spicy",
    performance: "Extreme Long Lasting",
    bottleStyle: "Square Black Bottle",
    tagline: "Leave a lasting presence.",
    gender: "Men",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/oud-eclipse.jpg",
    source: "NOREVA",
    offer: true,
    featured: true
  },
  {
    id: 3003,
    name: "Avent Noir",
    brand: "NŌRÉVA",
    collection: "VA SIGNATURE",
    category: "men-fragrance",
    tag: "Men",
    price: 1100,
    rating: 4.8,
    reviewCount: 92,
    inspiredBy: "Creed Aventus",
    description: "Fresh smoky masculine blend inspired by confidence, leadership, and modern luxury.",
    details: "Fresh citrus, smoky woods, and a refined masculine dry-down. Easy to wear daily with a clean premium signature.",
    fragranceFamily: "Fresh Woody",
    performance: "Strong Projection",
    bottleStyle: "Square Black Bottle",
    tagline: "A signature of confidence.",
    gender: "Men",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/avent-noir.jpg",
    source: "NOREVA",
    offer: true,
    featured: true
  },
  {
    id: 3004,
    name: "Xerion Gold",
    brand: "NŌRÉVA",
    collection: "VA ELIXIR",
    category: "men-fragrance",
    tag: "Men",
    price: 950,
    rating: 4.7,
    reviewCount: 68,
    inspiredBy: "Erba Pura",
    description: "Golden fruity luxury with smooth sensual notes and an addictive signature.",
    details: "A bright fruity amber scent with tropical warmth, soft musk, and a polished golden trail. Smooth and attention-grabbing.",
    fragranceFamily: "Fruity Amber",
    performance: "Long Lasting",
    bottleStyle: "Square Gold Bottle",
    tagline: "Luxury in every note.",
    gender: "Men",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/xerion-gold.jpg",
    source: "NOREVA",
    offer: true
  },
  {
    id: 3005,
    name: "Black Vanta",
    brand: "NŌRÉVA",
    collection: "VA PRIVÉ",
    category: "men-fragrance",
    tag: "Men",
    price: 1500,
    rating: 4.9,
    reviewCount: 71,
    inspiredBy: "Black Afgano",
    description: "Dark, intense, and mysterious with a bold niche-inspired character.",
    details: "A smoky dark woody fragrance with resinous depth and a daring trail. Made for strong personalities and evening wear.",
    fragranceFamily: "Dark Woody",
    performance: "Very Strong",
    bottleStyle: "Square Black Bottle",
    tagline: "Be unforgettable.",
    gender: "Men",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/black-vanta.jpg",
    source: "NOREVA",
    offer: true
  },
  {
    id: 3006,
    name: "Haciv Noir",
    brand: "NŌRÉVA",
    collection: "VA PRIVÉ",
    category: "men-fragrance",
    tag: "Men",
    price: 1300,
    rating: 4.8,
    reviewCount: 66,
    inspiredBy: "Nishane Hacivat",
    description: "Elegant citrus woods with refined freshness and exceptional long-lasting performance.",
    details: "Citrus freshness over polished woods and green accents. Sophisticated, clean, and suitable for day or night.",
    fragranceFamily: "Citrus Woody",
    performance: "Strong Projection",
    bottleStyle: "Square Green Bottle",
    tagline: "Modern luxury redefined.",
    gender: "Men",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/haciv-noir.jpg",
    source: "NOREVA",
    offer: true
  },
  {
    id: 3007,
    name: "Rose Velours",
    brand: "NŌRÉVA",
    collection: "VA FEMME",
    category: "women-fragrance",
    tag: "Women",
    price: 900,
    rating: 4.8,
    reviewCount: 88,
    inspiredBy: "Atomic Rose",
    description: "Velvety rose wrapped in warm sensual elegance and feminine softness.",
    details: "A rose amber fragrance with soft petals, warm depth, and a sensual elegant finish. Feminine, refined, and memorable.",
    fragranceFamily: "Rose Amber",
    performance: "Long Lasting",
    bottleStyle: "Round Feminine Bottle",
    tagline: "Elegance you can wear.",
    gender: "Women",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/rose-velours.jpg",
    source: "NOREVA",
    offer: true,
    featured: true
  },
  {
    id: 3008,
    name: "Delina Étoile",
    brand: "NŌRÉVA",
    collection: "VA FEMME",
    category: "women-fragrance",
    tag: "Women",
    price: 1100,
    rating: 4.8,
    reviewCount: 79,
    inspiredBy: "Delina Exclusif",
    description: "A luxurious floral vanilla blend with an elegant feminine aura.",
    details: "Soft floral notes meet creamy vanilla and a gentle powdery finish. A graceful scent for romantic and elegant moments.",
    fragranceFamily: "Floral Vanilla",
    performance: "Long Lasting",
    bottleStyle: "Round Feminine Bottle",
    tagline: "Soft. Feminine. Iconic.",
    gender: "Women",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/delina-etoile.jpg",
    source: "NOREVA",
    offer: true,
    featured: true
  },
  {
    id: 3009,
    name: "Valaya Lumière",
    brand: "NŌRÉVA",
    collection: "VA FEMME",
    category: "women-fragrance",
    tag: "Women",
    price: 850,
    rating: 4.7,
    reviewCount: 63,
    inspiredBy: "Valaya",
    description: "Clean silky fragrance with airy luxury vibes and delicate sophistication.",
    details: "A musky floral scent with clean softness, airy brightness, and a polished feminine trail. Fresh, gentle, and elegant.",
    fragranceFamily: "Musky Floral",
    performance: "Long Lasting",
    bottleStyle: "Round Luxe Bottle",
    tagline: "Pure elegance.",
    gender: "Women",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/valaya-lumiere.jpg",
    source: "NOREVA",
    offer: true,
    featured: true
  },
  {
    id: 3010,
    name: "Aura Guidance",
    brand: "NŌRÉVA",
    collection: "VA FEMME",
    category: "women-fragrance",
    tag: "Women",
    price: 1300,
    rating: 4.9,
    reviewCount: 91,
    inspiredBy: "Amouage Guidance",
    description: "Creamy white florals blended with warm amber and sensual depth.",
    details: "White florals, soft creaminess, and amber warmth create a rich feminine scent with refined depth and strong presence.",
    fragranceFamily: "Floral Amber",
    performance: "Exceptional Performance",
    bottleStyle: "Round Luxe Bottle",
    tagline: "Follow your signature.",
    gender: "Women",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/aura-guidance.jpg",
    source: "NOREVA",
    offer: true
  },
  {
    id: 3011,
    name: "Vanille Royale",
    brand: "NŌRÉVA",
    collection: "VA FEMME",
    category: "women-fragrance",
    tag: "Women",
    price: 950,
    rating: 4.8,
    reviewCount: 72,
    inspiredBy: "Roses Vanille",
    description: "Rich vanilla and rose combined in an addictive luxurious gourmand blend.",
    details: "Sweet vanilla, soft rose, and gourmand warmth in a smooth feminine fragrance that lingers beautifully.",
    fragranceFamily: "Vanilla Gourmand",
    performance: "Long Lasting",
    bottleStyle: "Round Feminine Bottle",
    tagline: "Luxury that lingers.",
    gender: "Women",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/vanille-royale.jpg",
    source: "NOREVA",
    offer: true
  },
  {
    id: 3012,
    name: "Jasmin Élégance",
    brand: "NŌRÉVA",
    collection: "VA FEMME",
    category: "women-fragrance",
    tag: "Women",
    price: 900,
    rating: 4.8,
    reviewCount: 69,
    inspiredBy: "Niche Jasmine Floral",
    description: "Elegant jasmine bouquet with refined sensuality and graceful floral depth.",
    details: "White jasmine and delicate florals with a refined soft finish. Elegant, feminine, and easy to love.",
    fragranceFamily: "White Floral",
    performance: "Long Lasting",
    bottleStyle: "Round Feminine Bottle",
    tagline: "A scent with presence.",
    gender: "Women",
    image: "https://k76j7fq9mn-jpg.github.io/noreva-beauty/assets/noreva-products/jasmin-elegance.jpg",
    source: "NOREVA",
    offer: true
  }
];

window.NOREVA_PRODUCTS = products;
